[project]
name = "spug-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=14.2.0",
    "ansible-runner>=2.4.3",
    "apscheduler==3.10.4",
    "asgiref==3.5.2",
    "boto3>=1.43.78",
    "channels==3.0.5",
    "channels-redis==3.4.1",
    "clickhouse-connect>=1.7.2",
    "cryptography>=49.0.0",
    "django==3.2.25",
    "django-redis==5.2.0",
    "gitpython==3.1.50",
    "openpyxl==3.0.3",
    "oss2>=2.19.1",
    "paramiko==3.4.0",
    "psycopg2-binary>=2.9.12",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.2",
    "python-ldap==3.4.7",
    "requests==2.32.4",
    "user-agents==2.2.0",
]
